
const cfg=window.V6_CONFIG;
const sb=window.supabase.createClient(cfg.SUPABASE_URL,cfg.SUPABASE_ANON_KEY);
const $=id=>document.getElementById(id);
let sessionUser=null,contexts=[],ctx=null;
function esc(s=''){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function fmt(n,d=1){return Number(n||0).toLocaleString('es-PE',{minimumFractionDigits:d,maximumFractionDigits:d})}
function today(){return new Date().toISOString().slice(0,10)}
function roleName(r){return ({supervisor:'Supervisor',superintendent:'Superintendente',construction_manager:'Gerente de Construcción',project_manager:'Gerente de Proyecto',project_controls:'Control de Proyecto',admin:'Administrador'})[r]||r}
async function login(){ $('loginMsg').textContent='Ingresando...'; const {data,error}=await sb.auth.signInWithPassword({email:$('email').value,password:$('password').value}); if(error){$('loginMsg').textContent=error.message;return} sessionUser=data.user; await startApp();}
async function logout(){await sb.auth.signOut();location.reload()}
async function startApp(){
 try{await sb.rpc('core_accept_my_invites')}catch(e){console.warn(e)}
 const {data,error}=await sb.from('core_v_user_context').select('*').eq('user_id',sessionUser.id);
 if(error){alert('No se pudo cargar tu contexto v6: '+error.message);return}
 contexts=data||[]; if(!contexts.length){$('loginMsg').textContent='Tu usuario aún no pertenece a ningún proyecto v6.';await sb.auth.signOut();return}
 ctx=contexts[0];
 $('loginSection').classList.add('hidden');$('appSection').classList.add('active');$('userBox').classList.remove('hidden');
 $('userBox').innerHTML=`<b>${esc(ctx.display_name||sessionUser.email)}</b><br>${esc(roleName(ctx.role))} · ${esc(ctx.project_name)}${ctx.discipline?'<br>'+esc(ctx.discipline):''}`;
 configureNav(); await showPage('home');
}
function configureNav(){const admin=['admin','project_manager','construction_manager'].includes(ctx.role),team=['admin','project_manager','construction_manager','superintendent'].includes(ctx.role);$('navAdmin').style.display=admin?'':'none';$('navTeam').style.display=team?'':'none'}
async function showPage(name){document.querySelectorAll('.page').forEach(x=>x.classList.add('hidden'));document.querySelectorAll('.nav button[id^=nav]').forEach(x=>x.classList.remove('active'));$('page'+name[0].toUpperCase()+name.slice(1)).classList.remove('hidden');const nav=$('nav'+name[0].toUpperCase()+name.slice(1));if(nav)nav.classList.add('active');if(name==='home')await renderHome();if(name==='plan')await renderPlan();if(name==='reports')await renderReports();if(name==='actions')await renderActions();if(name==='team')await renderTeam();if(name==='admin')await renderAdmin()}
async function renderHome(){if(ctx.role==='supervisor')return renderSupervisorHome();if(ctx.role==='superintendent')return renderSuperintendentHome();if(ctx.role==='construction_manager')return renderConstructionHome();return renderProjectHome()}
async function getMyTodaySummary(){const {data}=await sb.from('core_v_report_summary').select('*').eq('project_id',ctx.project_id).eq('member_id',ctx.member_id).eq('report_date',today());return data?.[0]||{}}
async function getTeamToday(){const {data}=await sb.from('core_v_team_daily_kpi').select('*').eq('project_id',ctx.project_id).eq('manager_member_id',ctx.member_id).eq('report_date',today());return data?.[0]||{}}
async function getSafetyToday(){let q=sb.from('core_v_safety_dashboard').select('*').eq('project_id',ctx.project_id).eq('report_date',today());if(ctx.discipline_id&&['supervisor','superintendent'].includes(ctx.role))q=q.eq('discipline_id',ctx.discipline_id);const {data}=await q;const rows=data||[];const hh=rows.reduce((s,x)=>s+Number(x.hh||0),0),incidents=rows.reduce((s,x)=>s+Number(x.incidents||0)+Number(x.accidents||0),0),req=rows.reduce((s,x)=>s+Number(x.preventive_required||0),0),done=rows.reduce((s,x)=>s+Number(x.preventive_done||0),0);return{hh,incidents,compliance:req?done/req*100:null}}
async function getQualityToday(){let q=sb.from('core_v_quality_dashboard').select('*').eq('project_id',ctx.project_id).eq('report_date',today());if(ctx.discipline_id&&['supervisor','superintendent'].includes(ctx.role))q=q.eq('discipline_id',ctx.discipline_id);const {data}=await q;const rows=data||[],total=rows.reduce((s,x)=>s+Number(x.quality_records||0),0),approved=rows.reduce((s,x)=>s+Number(x.approved_records||0),0);return{total,approved,pct:total?approved/total*100:null}}
async function getOpenCounts(){const [p,c,a]=await Promise.all([sb.from('core_procurement_requests').select('id',{count:'exact',head:true}).eq('project_id',ctx.project_id).not('status','in','("closed","cancelled")'),sb.from('core_constraints').select('id',{count:'exact',head:true}).eq('project_id',ctx.project_id).not('status','in','("closed","cancelled")'),sb.from('core_actions').select('id',{count:'exact',head:true}).eq('project_id',ctx.project_id).eq('assigned_member_id',ctx.member_id).not('status','in','("closed","cancelled")')]);return{proc:p.count||0,constraints:c.count||0,actions:a.count||0}}
function moduleCard(icon,title,desc,page){return `<div class="module" onclick="showPage('${page}')"><div class="icon">${icon}</div><h3>${title}</h3><p>${desc}</p></div>`}
async function renderSupervisorHome(){const[s,safety,quality,counts]=await Promise.all([getMyTodaySummary(),getSafetyToday(),getQualityToday(),getOpenCounts()]);$('pageHome').innerHTML=`<div class="card"><h2>Mi turno · ${today()}</h2><div class="kpis"><div class="kpi"><b>${fmt(s.people,0)}</b><span>Personal</span></div><div class="kpi"><b>${fmt(s.hh)}</b><span>HH</span></div><div class="kpi"><b>${fmt(s.equipment_qty,0)}</b><span>Equipos</span></div><div class="kpi"><b>${fmt(s.hm)}</b><span>HM</span></div><div class="kpi"><b>${fmt(s.activity_count,0)}</b><span>Actividades</span></div><div class="kpi"><b>${fmt(s.photo_count,0)}</b><span>Fotos</span></div></div></div><div class="modules">${moduleCard('🏗️','Producción','Actividades, metrados y fotografías','reports')}${moduleCard('👷','Personal / Equipos','Recursos del turno','reports')}${moduleCard('🦺','Seguridad',`${safety.incidents} eventos · ${safety.compliance==null?'—':fmt(safety.compliance,0)+'%'} cumplimiento`,'reports')}${moduleCard('✅','Calidad',`${quality.approved}/${quality.total} registros aprobados`,'reports')}${moduleCard('📦','Procura',`${counts.proc} requerimientos abiertos`,'reports')}${moduleCard('⚠️','Restricciones',`${counts.constraints} restricciones abiertas`,'reports')}</div><div class="card"><h2>Acciones para mí</h2><div class="kpis"><div class="kpi"><b>${counts.actions}</b><span>Pendientes</span></div></div><div class="actions"><button class="primary" onclick="showPage('actions')">Ver acciones</button></div></div>`}
function managementBlocks(safety,quality,counts){return `<div class="grid3"><div class="card"><h2>Seguridad</h2><div class="kpis" style="grid-template-columns:repeat(2,1fr)"><div class="kpi"><b>${safety.incidents}</b><span>Eventos</span></div><div class="kpi"><b>${safety.compliance==null?'—':fmt(safety.compliance,0)+'%'}</b><span>Cumplimiento</span></div></div></div><div class="card"><h2>Calidad</h2><div class="kpis" style="grid-template-columns:repeat(2,1fr)"><div class="kpi"><b>${quality.total}</b><span>Registros</span></div><div class="kpi"><b>${quality.pct==null?'—':fmt(quality.pct,0)+'%'}</b><span>Aprobación</span></div></div></div><div class="card"><h2>Alertas</h2><div class="kpis" style="grid-template-columns:repeat(2,1fr)"><div class="kpi"><b>${counts.proc}</b><span>Procura</span></div><div class="kpi"><b>${counts.constraints}</b><span>Restricciones</span></div></div></div></div>`}
async function renderSuperintendentHome(){const[t,safety,quality,counts]=await Promise.all([getTeamToday(),getSafetyToday(),getQualityToday(),getOpenCounts()]);$('pageHome').innerHTML=`<div class="card"><h2>${esc(ctx.discipline||'Disciplina')} · Consolidado de hoy</h2><div class="kpis"><div class="kpi"><b>${fmt(t.people,0)}</b><span>Personal</span></div><div class="kpi"><b>${fmt(t.hh)}</b><span>HH</span></div><div class="kpi"><b>${fmt(t.equipment_qty,0)}</b><span>Equipos</span></div><div class="kpi"><b>${fmt(t.hm)}</b><span>HM</span></div><div class="kpi"><b>${fmt(t.activities,0)}</b><span>Actividades</span></div><div class="kpi"><b>${fmt(t.reporting_members,0)}</b><span>Reportantes</span></div></div></div>${managementBlocks(safety,quality,counts)}<div class="card"><h2>Supervisores</h2><div id="directReports">Cargando...</div></div>`;await renderDirectReports()}
async function renderDirectReports(){const{data,error}=await sb.from('core_v_direct_reports').select('*').eq('project_id',ctx.project_id).eq('manager_member_id',ctx.member_id);const el=$('directReports');if(error){el.textContent=error.message;return}el.innerHTML=(data||[]).length?`<div class="table"><table><thead><tr><th>Nombre</th><th>Rol</th><th>Disciplina</th></tr></thead><tbody>${data.map(x=>`<tr><td>${esc(x.subordinate)}</td><td>${esc(roleName(x.role))}</td><td>${esc(x.discipline||'')}</td></tr>`).join('')}</tbody></table></div>`:'<span class="muted">Aún no hay supervisores asignados.</span>'}
async function renderConstructionHome(){const[t,safety,quality,counts]=await Promise.all([getTeamToday(),getSafetyToday(),getQualityToday(),getOpenCounts()]);$('pageHome').innerHTML=`<div class="card"><h2>Construction Dashboard · ${today()}</h2><div class="kpis"><div class="kpi"><b>${fmt(t.people,0)}</b><span>Personal</span></div><div class="kpi"><b>${fmt(t.hh)}</b><span>HH</span></div><div class="kpi"><b>${fmt(t.equipment_qty,0)}</b><span>Equipos</span></div><div class="kpi"><b>${fmt(t.hm)}</b><span>HM</span></div><div class="kpi"><b>${fmt(t.activities,0)}</b><span>Actividades</span></div><div class="kpi"><b>${counts.constraints}</b><span>Restricciones</span></div></div></div>${managementBlocks(safety,quality,counts)}<div class="card"><h2>Producción por disciplina</h2><div id="discProd">Cargando...</div></div>`;await renderProductionByDiscipline()}
async function renderProjectHome(){const[t,safety,quality,counts]=await Promise.all([getTeamToday(),getSafetyToday(),getQualityToday(),getOpenCounts()]);$('pageHome').innerHTML=`<div class="card"><h2>Project Executive Dashboard · ${today()}</h2><div class="kpis"><div class="kpi"><b>${fmt(t.people,0)}</b><span>Personal</span></div><div class="kpi"><b>${fmt(t.hh)}</b><span>HH</span></div><div class="kpi"><b>${fmt(t.hm)}</b><span>HM</span></div><div class="kpi"><b>${safety.incidents}</b><span>Eventos SST</span></div><div class="kpi"><b>${quality.pct==null?'—':fmt(quality.pct,0)+'%'}</b><span>Calidad</span></div><div class="kpi"><b>${counts.constraints}</b><span>Restricciones</span></div></div></div><div class="grid3"><div class="card"><h2>Project Health</h2><p class="muted">Cronograma, CPI/SPI y Forecast se activarán al cargar línea base/costos.</p><span class="badge">Schedule: pendiente plan</span></div><div class="card"><h2>Seguridad</h2><b>${safety.compliance==null?'—':fmt(safety.compliance,0)+'%'}</b> cumplimiento preventivo</div><div class="card"><h2>Calidad</h2><b>${quality.approved}/${quality.total}</b> registros aprobados</div></div><div class="card"><h2>Avance por disciplina</h2><div id="discProd">Cargando...</div></div>`;await renderProductionByDiscipline()}
async function renderProductionByDiscipline(){const{data,error}=await sb.from('core_v_daily_production').select('*').eq('project_id',ctx.project_id).eq('report_date',today());const el=$('discProd');if(error){el.textContent=error.message;return}const rows=data||[],grouped={};rows.forEach(x=>{const k=x.discipline_id||'sin';grouped[k]??={planned:0,actual:0};grouped[k].planned+=Number(x.planned_qty||0);grouped[k].actual+=Number(x.actual_qty||0)});const{data:disc}=await sb.from('core_disciplines').select('id,name').eq('project_id',ctx.project_id);const names=Object.fromEntries((disc||[]).map(x=>[x.id,x.name]));el.innerHTML=Object.entries(grouped).length?Object.entries(grouped).map(([k,v])=>{const pct=v.planned?v.actual/v.planned*100:0;return `<div style="margin:8px 0"><div style="display:flex;justify-content:space-between;font-size:11px"><b>${esc(names[k]||'Disciplina')}</b><span>${fmt(v.actual)} / ${fmt(v.planned)} (${fmt(pct,0)}%)</span></div><div class="bar"><span style="width:${Math.min(pct,100)}%"></span></div></div>`}).join(''):'<span class="muted">Sin producción registrada hoy.</span>'}
async function renderPlan(){const{data,error}=await sb.from('core_v_plan_vs_actual').select('*').eq('project_id',ctx.project_id).eq('plan_date',today()).order('item');$('pagePlan').innerHTML=`<div class="card"><h2>Plan Diario · ${today()}</h2>${error?esc(error.message):renderPlanTable(data||[])}</div>`}
function renderPlanTable(rows){if(!rows.length)return '<span class="muted">No hay actividades programadas para hoy.</span>';return `<div class="table"><table><thead><tr><th>Elemento</th><th>Partida</th><th>Und.</th><th>Plan</th><th>Real</th><th>Cumpl.</th></tr></thead><tbody>${rows.map(x=>`<tr><td>${esc(x.element)}</td><td>${esc(x.item)}</td><td>${esc(x.unit)}</td><td>${fmt(x.planned_qty)}</td><td>${fmt(x.actual_qty)}</td><td>${x.compliance_pct==null?'—':fmt(x.compliance_pct,0)+'%'}</td></tr>`).join('')}</tbody></table></div>`}
async function renderReports(){const{data,error}=await sb.from('core_v_report_summary').select('*').eq('project_id',ctx.project_id).order('report_date',{ascending:false}).limit(30);$('pageReports').innerHTML=`<div class="card"><h2>Reportes</h2>${error?esc(error.message):`<div class="table"><table><thead><tr><th>Fecha</th><th>Turno</th><th>Personal</th><th>HH</th><th>HM</th><th>Actividades</th><th>Fotos</th><th>Estado</th></tr></thead><tbody>${(data||[]).map(x=>`<tr><td>${esc(x.report_date)}</td><td>${esc(x.shift_name)}</td><td>${fmt(x.people,0)}</td><td>${fmt(x.hh)}</td><td>${fmt(x.hm)}</td><td>${fmt(x.activity_count,0)}</td><td>${fmt(x.photo_count,0)}</td><td><span class="badge">${esc(x.status)}</span></td></tr>`).join('')}</tbody></table></div>`}</div>`}
async function renderActions(){const{data,error}=await sb.from('core_actions').select('*').eq('project_id',ctx.project_id).order('created_at',{ascending:false}).limit(50);$('pageActions').innerHTML=`<div class="card"><h2>Acciones / Compromisos</h2>${error?esc(error.message):`<div class="table"><table><thead><tr><th>Acción</th><th>Prioridad</th><th>Fecha compromiso</th><th>Estado</th></tr></thead><tbody>${(data||[]).map(x=>`<tr><td>${esc(x.title)}</td><td>${esc(x.priority)}</td><td>${esc(x.due_date||'')}</td><td>${esc(x.status)}</td></tr>`).join('')}</tbody></table></div>`}</div>`}
async function renderTeam(){const{data,error}=await sb.from('core_v_organization').select('*').eq('project_id',ctx.project_id);$('pageTeam').innerHTML=`<div class="card"><h2>Organización</h2>${error?esc(error.message):`<div class="table"><table><thead><tr><th>Nombre</th><th>Rol</th><th>Disciplina</th><th>Reporta a</th></tr></thead><tbody>${(data||[]).map(x=>`<tr><td>${esc(x.display_name)}</td><td>${esc(roleName(x.role))}</td><td>${esc(x.discipline||'')}</td><td>${esc(x.reports_to||'')}</td></tr>`).join('')}</tbody></table></div>`}</div>`}
async function renderAdmin(){const can=['admin','project_manager','construction_manager'].includes(ctx.role);if(!can){$('pageAdmin').innerHTML='<div class="card">Sin permisos.</div>';return}const{data:disc}=await sb.from('core_disciplines').select('*').eq('project_id',ctx.project_id).eq('is_active',true).order('sort_order');const{data:members}=await sb.from('core_project_members').select('id,display_name,role,discipline_id').eq('project_id',ctx.project_id).eq('is_active',true);$('pageAdmin').innerHTML=`<div class="card"><h2>Invitar miembro</h2><div class="grid3"><div><label>Nombre</label><input id="invName"></div><div><label>Correo</label><input id="invEmail" type="email"></div><div><label>Rol</label><select id="invRole">${roleOptions(ctx.role)}</select></div><div><label>Disciplina</label><select id="invDisc"><option value="">—</option>${(disc||[]).map(x=>`<option value="${x.id}">${esc(x.name)}</option>`).join('')}</select></div><div><label>Reporta a</label><select id="invBoss"><option value="">—</option>${(members||[]).map(x=>`<option value="${x.id}">${esc(x.display_name)} · ${esc(roleName(x.role))}</option>`).join('')}</select></div></div><div class="actions"><button class="primary" onclick="sendInvite()">Crear invitación</button></div><div id="invMsg" class="muted"></div></div><div class="card"><h2>Proyecto</h2><p><b>${esc(ctx.project_name)}</b><br>${esc(ctx.company||'')} · ${esc(ctx.location||'')}</p></div>`}
function roleOptions(caller){let roles=['supervisor','superintendent','construction_manager','project_controls','project_manager'];if(caller==='construction_manager')roles=['supervisor','superintendent'];return roles.map(r=>`<option value="${r}">${roleName(r)}</option>`).join('')}
async function sendInvite(){const args={p_project_id:ctx.project_id,p_email:$('invEmail').value,p_role:$('invRole').value,p_display_name:$('invName').value||null,p_discipline_id:$('invDisc').value||null,p_reports_to_member_id:$('invBoss').value||null,p_front_ids:[]};const{error}=await sb.rpc('core_invite_member',args);$('invMsg').textContent=error?error.message:'Invitación creada correctamente.'}
(async function init(){const{data}=await sb.auth.getSession();if(data.session){sessionUser=data.session.user;await startApp()}})();
